# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  excalidraw
  labels:
    app: excalidraw
spec:
  selector:
    matchLabels:
      app: excalidraw
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: excalidraw
    spec:
      containers:
        - name: libreddit
          image: {{ .Values.excalidraw.image.registry }}/{{ .Values.excalidraw.image.repository }}:{{ .Values.excalidraw.image.tag }}
          ports:
            - containerPort: 80
              name: app
          # resources:
          #   requests:
          #     cpu: 50m
          #     memory: 50Mi
          #   limits:
          #     cpu: 250m
          #     memory: 200Mi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
      restartPolicy: Always
---
