# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: excalidraw
spec:
  selector:
    app: excalidraw
  type: ClusterIP
  ports:
  - name: excalidraw
    protocol: TCP
    port: 80
    targetPort: 80
---
